![IFMG](https://storage.googleapis.com/ifmg/IFMG.png)

---
# Matemática Computacional

## Sistemas Lineares

- Professor: Felipe Reis


---
### Importação de bibliotecas 

In [15]:
from __future__ import division
import numpy as np
import matplotlib.pyplot as plt
from numpy import linalg

---
## Eliminação Gaussiana 

### Eliminação Gaussiana via comandos Python passo-a-passo

Considere o sistema linear:

$x + y + z = 1$

$4x + 4y + 2z = 2$

$2x + y − z = 0$

Podemos escrever ele na forma de matriz, utilizando comandos Python, com o seguinte comando

In [16]:
E = np.array([
    [1, 1, 1, 1],
    [4, 4, 2, 2],
    [2, 1,-1, 0]], dtype='double')

print(E)

[[ 1.  1.  1.  1.]
 [ 4.  4.  2.  2.]
 [ 2.  1. -1.  0.]]


Podemos escrever cada uma das linhas (L1, L2 e L3) com os seguintes comandos

In [17]:
L1 = E[0,:]
L2 = E[1,:]
L3 = E[2,:]

print(L1)
print(L2)
print(L3)

[1. 1. 1. 1.]
[4. 4. 2. 2.]
[ 2.  1. -1.  0.]


Fazemos no primeiro passo do escalonamento as seguintes operações:

* $L_2 \leftarrow L_2 − 4 L_1$
* $L_3 \leftarrow L_3 − 2 L_1$

In [18]:
#observação: cuidado ao rodar o script múltiplas vezes
#o cálculo da mesma linha múltiplas vezes pode produzir resultados indesejados

L2 = L2 - (4*L1)  #alternativamente, L2 -= (4L1)
L3 -= (2*L1)

print(L2)
print(L3)

[ 0.  0. -2. -2.]
[ 0. -1. -3. -2.]


Podemos voltar o resultado do primeiro escalonamento para a matriz original.

In [19]:
#E[0,:] = L1
E[1,:] = L2
E[2,:] = L3

print(E)

[[ 1.  1.  1.  1.]
 [ 0.  0. -2. -2.]
 [ 0. -1. -3. -2.]]


### Resolução do Sistema Linear usando biblioteca Numpy

* https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html

Considere o sistema linear:

$x + y + z = 1$

$4x + 4y + 2z = 2$

$2x + y − z = 0$

In [20]:
A = np.array([
    [1, 1, 1],
    [4, 4, 2],
    [2, 1,-1]], dtype='double')

B = np.array([[1],[2],[0]])
#B = np.array([1,2,0]) #também soluciona, porém retorna o resultado em outro formato

print(A)
print(B)

[[ 1.  1.  1.]
 [ 4.  4.  2.]
 [ 2.  1. -1.]]
[[1]
 [2]
 [0]]


In [21]:
S = np.linalg.solve(A, B)
print(S)

[[ 1.]
 [-1.]
 [ 1.]]


In [22]:
A = np.array([
    [3, 3, 1],
    [1, 1, 2],
    [3, 1, 3]], dtype='double')

B = np.array([[1],[2],[4]])
#B = np.array([1,2,0]) #também soluciona, porém retorna o resultado em outro formato

print(A)
print(B)

S = np.linalg.solve(A, B)
print(S)

[[3. 3. 1.]
 [1. 1. 2.]
 [3. 1. 3.]]
[[1]
 [2]
 [4]]
[[ 0.5]
 [-0.5]
 [ 1. ]]


---
## Fatoração LU

* Código disponível na página 105 do livro:

Justo, D., Sauter, E., Azevedo, F., Guidi, L., and Konzen, P. H. (2020). **Cálculo Numérico, Um Livro Colaborativo - Versão Python.** UFRGS - Universidade Federal do Rio Grande do Sul. Disponível em: https://www.ufrgs.br/reamat/CalculoNumerico/livro-py/livro-py.pdf.

In [23]:
def fatoraLU(A):
    U = np.copy(A)
    n = np.shape(U)[0]
    L = np.eye(n)
    for j in np.arange(n-1):
        for i in np.arange(j+1,n):
            L[i,j] = U[i,j]/U[j,j]
            for k in np.arange(j+1,n):
                U[i,k] = U[i,k] - L[i,j]*U[j,k]
            U[i,j] = 0
    return L, U


#### Solução do sistema linear abaixo (slide 37):

$x_1 + x_2 + x_3 = -2$

$2 x_1 + x_2 - x_3 = -1$

$2 x_1 - x_2 + x_3 = 1$

In [24]:
A = np.array([
    [1,  1,  1],
    [2,  1, -1],
    [2, -1,  1]], dtype='double')

L, U = fatoraLU(A)

print('Matriz L \n', L)
print()
print('Matriz U \n', U)

Matriz L 
 [[1. 0. 0.]
 [2. 1. 0.]
 [2. 3. 1.]]

Matriz U 
 [[ 1.  1.  1.]
 [ 0. -1. -3.]
 [ 0.  0.  8.]]


#### Solução do sistema linear abaixo (Ruggiero e Lopes):

* Ruggiero, M. A. G. and Lopes, V. L. d. R. (2000). **Cálculo Numérico - Aspectos Teóricos e Computacionais.** Editora Makron, 2 edition.

$3 x_1 + 2 x_2 + 4 x_3 = 1$

$x_1 + x_2 + 2 x_3 = 2$
  
$4 x_1 + 3 x_2 + 2 x_3 = 3$

In [25]:
A = np.array([
    [3,  2,  4],
    [1,  1,  2],
    [4,  3,  2]], dtype='double')

L, U = fatoraLU(A)

print('Matriz L \n', L)
print()
print('Matriz U \n', U)

Matriz L 
 [[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [1.33333333 1.         1.        ]]

Matriz U 
 [[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -4.        ]]


---
## Método de Jacobi

* Código disponível na página 124 do livro:

Justo, D., Sauter, E., Azevedo, F., Guidi, L., and Konzen, P. H. (2020). **Cálculo Numérico, Um Livro Colaborativo - Versão Python.** UFRGS - Universidade Federal do Rio Grande do Sul. Disponível em: https://www.ufrgs.br/reamat/CalculoNumerico/livro-py/livro-py.pdf.

In [32]:
def jacobi(A, b, x0, tol, N):
    #preliminares
    A = A.astype('double')
    b = b.astype('double')
    x0 = x0.astype('double')
    
    n=np.shape(A)[0]
    x = np.zeros(n)
    it = 0
    
    arr = []
    
    #iteracoes
    while (it < N):
        it = it+1
        #iteracao de Jacobi
        for i in np.arange(n):
            x[i] = b[i]
            
            for j in np.arange(n): 
                if(i != j):
                    x[i] -= A[i,j]*x0[j]
                    
            x[i] /= A[i,i]
        
        arr.append(x.copy())
        
        #tolerancia (verifica a norma do vetor)
        if (np.linalg.norm(x-x0,np.inf) < tol):
            return x, arr
        
        #prepara nova iteracao
        x0 = np.copy(x)
    
    raise NameError('num. max. de iteracoes excedido.')

#### Solução do sistema linear abaixo (slide 57):

$10x + y = 23$

$x + 8y = 26$

In [33]:
A = np.array([
    [10, 1,],
    [1, 8]], dtype='double')

B = np.array([[23],[26]], dtype='double')
x0 = np.array([[0],[0]], dtype='double')

x, arr = jacobi(A, B, x0, 0.0000001, 500)
print(x)
print(arr)

[2.00000001 3.00000001]
[array([2.3 , 3.25]), array([1.975 , 2.9625]), array([2.00375 , 3.003125]), array([1.9996875 , 2.99953125]), array([2.00004687, 3.00003906]), array([1.99999609, 2.99999414]), array([2.00000059, 3.00000049]), array([1.99999995, 2.99999993])]


In [34]:
nx, ny = 2, 3

err_x = []

for a in arr:
    err_abs_x, err_rel_x = calc_erro(nx, a[0])
    err_abs_y, err_rel_y = calc_erro(ny, a[1])

[2.3  3.25]
[1.975  2.9625]
[2.00375  3.003125]
[1.9996875  2.99953125]
[2.00004687 3.00003906]
[1.99999609 2.99999414]
[2.00000059 3.00000049]
[1.99999995 2.99999993]


---
## Método de Gauss-Seidel

* Código disponível na página 126 do livro:

Justo, D., Sauter, E., Azevedo, F., Guidi, L., and Konzen, P. H. (2020). **Cálculo Numérico, Um Livro Colaborativo - Versão Python.** UFRGS - Universidade Federal do Rio Grande do Sul. Disponível em: https://www.ufrgs.br/reamat/CalculoNumerico/livro-py/livro-py.pdf.

In [13]:
def gauss_seidel(A, b, x0, tol, N):
    #preliminares
    A = A.astype('double')
    b = b.astype('double')
    x0 = x0.astype('double')
    
    n=np.shape(A)[0]
    x = np.copy(x0)
    it = 0
    
    #iteracoes
    while (it < N):
        it = it+1
        #iteracao de Gauss-Seidel
        for i in np.arange(n):
            x[i] = b[i]
            
            #gera todas as posições da matriz, exceto a diagonal principal
            #equivalente a "for j in np.arange(n): if(i != j):"
            for j in np.concatenate((np.arange(0,i),np.arange(i+1,n))):
                x[i] -= A[i,j]*x[j]
            x[i] /= A[i,i]
            
        #tolerancia (verifica a norma do vetor)
        if (np.linalg.norm(x-x0,np.inf) < tol):
            return x
        
        print(x)
        
        #prepara nova iteracao
        x0 = np.copy(x)
        
    raise NameError('num. max. de iteracoes excedido.')

#### Solução do sistema linear abaixo (slide 57):

$10x + y = 23$

$x + 8y = 26$

In [14]:
A = np.array([
    [10, 1,],
    [1, 8]], dtype='double')

B = np.array([[23],[26]], dtype='double')
x0 = np.array([[0],[0]], dtype='double')

x = gauss_seidel(A, B, x0, 0.000001, 500)
print(x)

[[2.3   ]
 [2.9625]]
[[2.00375   ]
 [2.99953125]]
[[2.00004687]
 [2.99999414]]
[[2.00000059]
 [2.99999993]]
[[2.00000001]
 [3.        ]]
